export const DEFAULT_COUNTRY_REGION_MAP: Record<string, string> = {
  australia: "APAC",
  austria: "EMEA",
  belgium: "EMEA",
  brazil: "LATAM",
  canada: "NAMER",
  china: "APAC",
  france: "EMEA",
  germany: "EMEA",
  "hong kong": "APAC",
  india: "APAC",
  ireland: "EMEA",
  israel: "EMEA",
  italy: "EMEA",
  japan: "APAC",
  malaysia: "APAC",
  mexico: "LATAM",
  netherlands: "EMEA",
  singapore: "APAC",
  spain: "EMEA",
  sweden: "EMEA",
  "united arab emirates": "EMEA",
  "united kingdom": "EMEA",
  "united states of america": "NAMER",
};
